#!/usr/bin/env python3
"""Write a SYNTHETIC side-scan XTF file with known ground truth.

    python3 tools/make_synthetic_xtf.py                       # samples/synthetic_xtf/
    python3 tools/make_synthetic_xtf.py --out /tmp/x --pings 1600 --seed 57
    python3 tools/make_synthetic_xtf.py --start-time 2026-09-06T04:30:00Z
    python3 tools/make_synthetic_xtf.py --scenario repeat --name SYNTHETIC_mannar_line02 \
        --start-time 2026-09-09T04:30:00Z                     # the same line, re-surveyed

EVERYTHING THIS WRITES IS SYNTHETIC. No sonar was deployed and no object or
fish exists. The XTF file header's NoteString, an XTF notes packet at the start
of the file, and the ground-truth JSON all say so, and sonar_ingest reads that
marking and carries `"synthetic": true` into every strip it produces. The point
of the file is to exercise the real ingest path -- a genuine XTF parsed by
pyxtf, with real ping headers -- against positions that are known exactly,
which no public survey offers.

The line runs roughly east-west in the Gulf of Mannar, near the Marine National
Park island chain (about 9.12 N, 79.05 E), in 8 to 18 m of water. The place is
chosen because ghost nets and reef fish are the survey problem there. Nothing
about the seabed below is a model of the real one.

WHY IT IS BUILT FROM GEOMETRY, NOT PAINTED
    A painted strip tests nothing about georeferencing: the pixel positions
    would be whatever the painter chose. Here a towfish is flown along a
    curving track, each ping's samples are generated by casting the beam's
    slant ranges onto a height field of the seabed, and ground truth is the
    objects' true positions on that seabed. So a target only appears where
    slant-range geometry, heading and navigation put it, and ingesting the file
    back has to undo all three to find it again.

THE PHYSICS, AND ITS LIMITS
    slant sample k      r = k * SlantRange / NumSamples
    ground point        g = sqrt(r^2 - a^2) across-track from the fish, a = altitude
    return strength     reflectivity * sin(grazing angle + facet slope)^1.2
    acoustic shadow     a point is dark when a nearer, taller point already
                        blocks the ray (running minimum of depression angle)
    speckle             multiplicative Rayleigh, unit mean
    roll                port/starboard gain imbalance
    pitch               energy loss and a fore/aft footprint shift r*sin(pitch)
    heave               moves the sensor up and down, changing its altitude
    water depth         8..18 m; the fish tows at a fixed depth, so the seabed
                        shoaling under it changes the altitude

    Not modelled: layover (object heights do not shorten their slant range),
    multipath, refraction, beam pattern beyond a smooth gain, yaw/crab, fish
    shadows on the seabed.

INJECTED DEFECTS (all recorded in the truth file)
    attitude excursion  a segment of heavy pitch, roll and heave
    time-gap dropout    pings never written; the clock jumps, the fish moves on
    empty pings         pings written with all-zero samples

TARGETS (all recorded in the truth file with true lat/lon and size)
    cylinder x2         2.0 m x 0.5 m, metal, strong highlight and shadow
    pipe                long, thin, oblique to the track
    shipwreck           24 m x 7 m hull in shallow water
    net x2              draped, irregular, faint mesh
    rock cluster        natural boulders: false-positive bait, not man-made
    sand ripples        seabed texture over part of the line

FISH IN THE WATER COLUMN
    A fish is a point scatterer at a fixed depth. A ping sees it when it lies
    inside the beam's fore/aft footprint on that channel's side, and its echo
    lands at its true slant range: in the water column, before the first bottom
    return, when it is close enough across-track, and over the seabed returns
    otherwise.

    net T5      dense schools above and around it, on its side, spread about
                30 m along-track: the signature of a net still ghost-fishing.
                "fish_aggregation": true.
    net T7      the control: same side, similar cross-track distance, similar
                water depth, and no aggregation. "fish_aggregation": false.
    elsewhere   sparse single fish on both sides, as background. None is placed
                inside T5's aggregation window, so the aggregation is exactly
                what the truth file lists.

SCENARIOS (--scenario)
    baseline    the line as described above (the default; unchanged output).
    repeat      the SAME track flown again later (use --start-time), for
                testing change tracking across surveys:
                  T5  MOVED about REPEAT_MOVE_M (40 m) along and across the
                      track, still ghost-fishing (the aggregation moves with it)
                  T7  REMOVED: not on the seabed any more
                  T8  NEW net elsewhere inside the swath, no aggregation
                  every other target is where it was
                Seabed shapes come from the same seed, so unchanged targets
                look the same; speckle and background fish come from a
                different stream, as a second recording would. The truth file
                records every change under "scenario_changes".
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from survey_hazard_map.hazard_geo import offset_latlon  # noqa: E402

SYNTHETIC_NOTE = "SYNTHETIC DATA - tools/make_synthetic_xtf.py - not a real survey"

# Gulf of Mannar, near the Marine National Park islands.
ORIGIN_LAT = 9.1200
ORIGIN_LON = 79.0500
START_TIME = datetime(2026, 9, 1, 4, 30, 0, tzinfo=timezone.utc)
SCENARIOS = ("baseline", "repeat")
# Repeat scenario: how far T5 moves, and its new cross-track distance.
REPEAT_MOVE_M = 40.0
REPEAT_T5_CROSS_M = 21.0

SLANT_RANGE_M = 50.0
PING_INTERVAL_S = 0.1
# The towfish tows at a fixed depth; the seabed shoals and deepens under it.
SENSOR_DEPTH_M = 2.5
KNOTS_PER_MPS = 1.0 / 0.514444
COUNTS_SCALE = 6000.0

# Fish echoes. The fore/aft footprint is the beam plus the fish's own length,
# so a fish is seen by a handful of consecutive pings, as in real records.
FISH_FOOTPRINT_M = 0.35
FISH_ECHO_WIDTH_M = 0.12
FISH_ECHO_STRENGTH = (0.9, 2.2)


def _track(pings: int, dt: float):
    """Towfish state per ping in local east/north metres. All numpy arrays."""
    import numpy as np

    t = np.arange(pings) * dt
    duration = max(t[-1], dt)
    speed = 2.0 + 0.45 * np.sin(2 * np.pi * t / 90.0) + 0.2 * np.sin(2 * np.pi * t / 23.0)
    # Roughly east-west along the island chain, gently curving.
    heading = (95.0 + 12.0 * np.sin(np.pi * t / duration)
               - 5.0 * np.sin(3 * np.pi * t / duration)) % 360
    rad = np.radians(heading)
    east = np.concatenate([[0.0], np.cumsum(speed[:-1] * dt * np.sin(rad[:-1]))])
    north = np.concatenate([[0.0], np.cumsum(speed[:-1] * dt * np.cos(rad[:-1]))])
    along = np.concatenate([[0.0], np.cumsum(speed[:-1] * dt)])
    heave = 0.08 * np.sin(2 * np.pi * t / 6.5)
    pitch = 0.8 * np.sin(2 * np.pi * t / 9.0)
    roll = 1.2 * np.sin(2 * np.pi * t / 7.0)
    # Water depth 8..18 m, deepest over both nets so the control comparison is
    # made in the same depth of water.
    depth = 13.0 + 5.0 * np.cos(2 * np.pi * (t / duration - 0.74) / 0.56)
    return {"t": t, "speed": speed, "heading": heading, "east": east, "north": north,
            "along": along, "heave": heave, "pitch": pitch, "roll": roll, "depth": depth}


def _altitude(track: dict):
    """Sensor height above the seabed. Heave positive = sensor up."""
    return track["depth"] - (SENSOR_DEPTH_M - track["heave"])


def _target_en(track: dict, ping: int, cross: float) -> tuple[float, float]:
    """East/north of a point `cross` metres to starboard of the towfish at `ping`."""
    hr = math.radians(float(track["heading"][ping]))
    return (float(track["east"][ping]) + cross * math.cos(hr),
            float(track["north"][ping]) - cross * math.sin(hr))


def _layout(pings: int, scenario: str = "baseline", track: dict | None = None) -> dict:
    """Where defects and targets go, as fractions of the line so --pings scales it."""
    def at(fraction: float) -> int:
        return int(round(fraction * pings))

    layout = _baseline_layout(pings, at)
    if scenario == "baseline":
        return layout
    if scenario != "repeat":
        raise ValueError(f"unknown scenario {scenario!r}; choose from {SCENARIOS}")
    if track is None:
        raise ValueError("the repeat scenario needs the track to place the moved net")
    targets = []
    changes = []
    for entry in layout["targets"]:
        tid, cls, ping, cross, kind, params = entry
        if tid == "T7":
            changes.append({"id": "T7", "change": "removed",
                            "note": "not on the seabed in the repeat survey"})
            continue
        if tid == "T5":
            old = _target_en(track, ping, cross)
            # The abeam ping (searched backwards along the line) whose new
            # position is closest to REPEAT_MOVE_M from the old one.
            best = min(range(max(0, ping - 600), ping),
                       key=lambda q: abs(math.dist(old, _target_en(track, q, REPEAT_T5_CROSS_M))
                                         - REPEAT_MOVE_M))
            new = _target_en(track, best, REPEAT_T5_CROSS_M)
            from_lat, from_lon = offset_latlon(ORIGIN_LAT, ORIGIN_LON, old[0], old[1])
            changes.append({"id": "T5", "change": "moved",
                            "displacement_m": round(math.dist(old, new), 2),
                            "from_latitude": round(from_lat, 8), "from_longitude": round(from_lon, 8),
                            "from_ping_abeam": int(ping), "from_cross_track_m": cross,
                            "to_ping_abeam": int(best), "to_cross_track_m": REPEAT_T5_CROSS_M})
            entry = (tid, cls, best, REPEAT_T5_CROSS_M, kind, params)
        targets.append(entry)
    targets.append(("T8", "net", at(0.44), -12.0, "net",
                    {"length": 7.0, "width": 5.0, "orient": 35.0,
                     "note": "faint draped mesh, no aggregation: a net that arrived since the "
                             "baseline line"}))
    changes.append({"id": "T8", "change": "new", "note": "not present in the baseline line"})
    layout["targets"] = targets
    layout["scenario_changes"] = changes
    layout["control_net"] = "T8"
    return layout


def _baseline_layout(pings: int, at) -> dict:
    return {
        "attitude": (at(0.27), at(0.325)),
        "gap": (at(0.515), at(0.515) + max(10, at(0.019))),
        "empty": (at(0.5625), at(0.5625) + 3),
        "targets": [
            # id, class, ping abeam, cross-track m (+ starboard), kind, params
            ("T1", "cylinder", at(0.094), 18.0, "cylinder",
             {"length": 2.0, "diameter": 0.5, "orient": 30.0}),
            ("T2", "rock", at(0.21), -22.0, "rocks", {"radius": 7.0, "count": 14}),
            ("T3", "shipwreck", at(0.37), 26.0, "wreck",
             {"length": 24.0, "beam": 7.0, "height": 2.5, "orient": 40.0}),
            ("T4", "cylinder", at(0.625), -14.0, "cylinder",
             {"length": 2.0, "diameter": 0.5, "orient": -60.0}),
            ("T5", "net", at(0.74), 16.0, "net", {"length": 9.0, "width": 6.0, "orient": 15.0}),
            ("T6", "pipe", at(0.865), -30.0, "cylinder",
             {"length": 34.0, "diameter": 0.6, "orient": 75.0}),
            ("T7", "net", at(0.18), 17.0, "net", {"length": 8.0, "width": 6.5, "orient": -20.0}),
        ],
        # The net that is ghost-fishing. T7 is the control and gets nothing.
        "aggregation_net": "T5",
        "control_net": "T7",
        "scenario_changes": [],
        "ripples": (at(0.66), at(0.84)),
    }


class Seabed:
    """A height field and reflectivity map in local east/north metres."""

    def __init__(self, track: dict, layout: dict, rng) -> None:
        import numpy as np

        self.objects: list[dict] = []
        self.truth: list[dict] = []
        e, n, h = track["east"], track["north"], track["heading"]

        for tid, cls, ping, cross, kind, params in layout["targets"]:
            heading = float(h[ping])
            hr = math.radians(heading)
            sx, sy = math.cos(hr), -math.sin(hr)          # starboard unit (east, north)
            ce = float(e[ping]) + cross * sx
            cn = float(n[ping]) + cross * sy
            lat, lon = offset_latlon(ORIGIN_LAT, ORIGIN_LON, ce, cn)
            entry = {"id": tid, "class": cls, "latitude": round(lat, 8),
                     "longitude": round(lon, 8), "east_m": round(ce, 3),
                     "north_m": round(cn, 3), "side": "starboard" if cross > 0 else "port",
                     "cross_track_m": cross, "track_heading_deg": round(heading, 3),
                     "ping_index_abeam": int(ping),
                     "along_track_m": round(float(track["along"][ping]), 2),
                     "water_depth_m": round(float(track["depth"][ping]), 2),
                     "fish_aggregation": tid == layout["aggregation_net"]}
            if kind == "cylinder":
                bearing = (heading + params["orient"]) % 360
                self.objects.append({"kind": "cylinder", "ce": ce, "cn": cn,
                                     "bearing": bearing, "length": params["length"],
                                     "radius": params["diameter"] / 2.0,
                                     "refl": 4.0 if cls == "cylinder" else 3.0})
                entry.update({"length_m": params["length"], "width_m": params["diameter"],
                              "height_m": params["diameter"],
                              "orientation_deg": round(bearing, 2), "man_made": True})
            elif kind == "wreck":
                bearing = (heading + params["orient"]) % 360
                self.objects.append({"kind": "wreck", "ce": ce, "cn": cn, "bearing": bearing,
                                     "length": params["length"], "beam": params["beam"],
                                     "height": params["height"], "refl": 2.6,
                                     "holes": rng.uniform(-1, 1, size=(6, 2)),
                                     "phase": rng.uniform(0, 6.28, size=3)})
                entry.update({"length_m": params["length"], "width_m": params["beam"],
                              "height_m": params["height"] + 0.8,
                              "orientation_deg": round(bearing, 2), "man_made": True})
            elif kind == "net":
                bearing = (heading + params["orient"]) % 360
                self.objects.append({"kind": "net", "ce": ce, "cn": cn, "bearing": bearing,
                                     "length": params["length"], "width": params["width"],
                                     "phase": rng.uniform(0, 6.28, size=3)})
                entry.update({"length_m": params["length"], "width_m": params["width"],
                              "height_m": 0.3, "orientation_deg": round(bearing, 2),
                              "man_made": True,
                              "note": params.get("note") or (
                                  "faint draped mesh with a dense fish aggregation above "
                                  "it: actively ghost-fishing"
                                  if entry["fish_aggregation"] else
                                  "faint draped mesh, no aggregation: the control case")})
            elif kind == "rocks":
                boulders = []
                for _ in range(params["count"]):
                    r = params["radius"] * math.sqrt(rng.uniform(0, 1))
                    a = rng.uniform(0, 2 * math.pi)
                    boulders.append({"kind": "boulder", "ce": ce + r * math.cos(a),
                                     "cn": cn + r * math.sin(a),
                                     "radius": float(rng.uniform(0.5, 1.4)),
                                     "height": float(rng.uniform(0.3, 1.2)),
                                     "refl": float(rng.uniform(1.5, 2.2))})
                self.objects.extend(boulders)
                entry.update({"length_m": 2 * params["radius"], "width_m": 2 * params["radius"],
                              "height_m": round(max(b["height"] for b in boulders), 2),
                              "orientation_deg": None, "man_made": False,
                              "boulders": len(boulders),
                              "note": "natural rock cluster: false-positive bait, not a hazard"})
            self.truth.append(entry)

        r0, r1 = layout["ripples"]
        self.ripple_centre = ((e[r0] + e[r1]) / 2.0, (n[r0] + n[r1]) / 2.0)
        self.ripple_radius = max(30.0, float(np.hypot(e[r1] - e[r0], n[r1] - n[r0])) / 2.0 + 20.0)

    def sample(self, E, N):
        """(height m, reflectivity) at arrays of east/north positions."""
        import numpy as np

        height = np.zeros_like(E)
        refl = 1.0 + 0.15 * np.sin(E / 37.0) * np.cos(N / 23.0) + 0.05 * np.sin((E + N) / 5.3)

        # Sand ripples: crests 1.1 m apart, fading out at the patch edge.
        dr = np.hypot(E - self.ripple_centre[0], N - self.ripple_centre[1])
        fade = np.clip(1.0 - dr / self.ripple_radius, 0.0, 1.0) ** 0.5
        refl = refl * (1.0 + 0.38 * fade * np.sin(2 * np.pi * (0.8 * E + 0.6 * N) / 1.1))

        for obj in self.objects:
            reach = obj.get("length", 0.0) / 2 + obj.get("beam", 0.0) + obj.get("width", 0.0) \
                + obj.get("radius", 0.0) + 1.0
            box = (np.abs(E - obj["ce"]) < reach) & (np.abs(N - obj["cn"]) < reach)
            if not box.any():
                continue
            de, dn = E[box] - obj["ce"], N[box] - obj["cn"]
            if obj["kind"] == "boulder":
                d = np.hypot(de, dn) / obj["radius"]
                h = np.where(d < 1.0, obj["height"] * np.sqrt(np.clip(1 - d * d, 0, 1)), 0.0)
                h = h * (1.0 + 0.15 * np.sin(de * 7.0) * np.cos(dn * 5.0))
                r = np.full_like(h, obj["refl"])
            else:
                b = math.radians(obj["bearing"])
                ux, uy = math.sin(b), math.cos(b)
                u = de * ux + dn * uy                      # along the object's axis
                v = de * uy - dn * ux                      # across it
                if obj["kind"] == "cylinder":
                    R = obj["radius"]
                    inside = (np.abs(u) <= obj["length"] / 2) & (np.abs(v) < R)
                    h = np.where(inside, R + np.sqrt(np.clip(R * R - v * v, 0, None)), 0.0)
                    r = np.full_like(h, obj["refl"])
                elif obj["kind"] == "wreck":
                    L, B, H = obj["length"], obj["beam"], obj["height"]
                    half_beam = (B / 2) * np.sqrt(np.clip(1 - (2 * u / L) ** 4, 0, 1))
                    inside = (np.abs(u) <= L / 2) & (np.abs(v) < half_beam)
                    hull = H * np.sqrt(np.clip(1 - (v / np.maximum(half_beam, 1e-6)) ** 2, 0, 1))
                    p = obj["phase"]
                    hull *= 0.75 + 0.25 * np.sin(u * 1.7 + p[0]) * np.cos(v * 2.3 + p[1])
                    deck = (np.abs(u + 2.0) < 3.5) & (np.abs(v) < B / 4)
                    hull = np.where(deck, hull + 0.8, hull)
                    for hx, hy in obj["holes"]:
                        hole = np.hypot(u - hx * L / 2.5, v - hy * B / 3) < 1.4
                        hull = np.where(hole, hull * 0.25, hull)
                    h = np.where(inside, hull, 0.0)
                    r = np.full_like(h, obj["refl"]) * (0.8 + 0.4 * np.abs(np.sin(u * 3.1 + p[2])))
                else:  # net
                    L, W = obj["length"], obj["width"]
                    p = obj["phase"]
                    ang = np.arctan2(v, u)
                    edge = 1.0 + 0.25 * np.sin(3 * ang + p[0]) + 0.15 * np.sin(5 * ang + p[1])
                    radial = np.hypot(2 * u / L, 2 * v / W)
                    inside = radial < edge
                    mesh = (np.abs(np.sin(np.pi * (u + 0.3 * np.sin(v)) / 0.6)) < 0.3) | \
                           (np.abs(np.sin(np.pi * (v + 0.3 * np.sin(u * 0.7)) / 0.6)) < 0.3)
                    folds = 0.18 * np.clip(np.sin(u * 0.9 + p[2]) * np.cos(v * 1.3), 0, None)
                    h = np.where(inside, np.where(mesh, 0.12, 0.03) + folds, 0.0)
                    r = np.where(inside & mesh, 1.55, 1.05)
            sub_h = height[box]
            sub_r = refl[box]
            take = h > sub_h
            sub_h[take] = h[take]
            present = h > 0.01
            sub_r[present] = r[present]
            height[box] = sub_h
            refl[box] = sub_r
        return height, refl


def _fish(track: dict, layout: dict, seabed: Seabed, rng) -> tuple[list[dict], list[dict]]:
    """Fish as point scatterers, and the schools they belong to, for the truth file."""
    e, n, h, depth = track["east"], track["north"], track["heading"], track["depth"]
    along = track["along"]
    pings = len(e)
    fish: list[dict] = []
    schools: list[dict] = []

    def place(ping: int, along_off: float, cross: float) -> tuple[float, float, float]:
        hr = math.radians(float(h[ping]))
        fx, fy = math.sin(hr), math.cos(hr)              # forward unit
        sx, sy = math.cos(hr), -math.sin(hr)             # starboard unit
        return (float(e[ping]) + along_off * fx + cross * sx,
                float(n[ping]) + along_off * fy + cross * sy, float(depth[ping]))

    net = next(t for t in seabed.truth if t["id"] == layout["aggregation_net"])
    side = 1.0 if net["cross_track_m"] > 0 else -1.0
    window = (net["along_track_m"] - 16.0, net["along_track_m"] + 16.0)
    for index in range(8):
        along_off = float(rng.uniform(-15.0, 15.0))
        cross = side * float(rng.uniform(3.0, 13.0))
        ce, cn, water = place(net["ping_index_abeam"], along_off, cross)
        centre_depth = SENSOR_DEPTH_M + float(rng.uniform(0.35, 0.7)) * (water - SENSOR_DEPTH_M)
        count = int(rng.integers(10, 22))
        members = 0
        for _ in range(count):
            fe = ce + float(rng.normal(0, 1.2))
            fn = cn + float(rng.normal(0, 1.2))
            fz = min(max(centre_depth + float(rng.normal(0, 0.6)), SENSOR_DEPTH_M + 0.8),
                     water - 0.5)
            fish.append({"east": fe, "north": fn, "depth": fz,
                         "strength": float(rng.uniform(*FISH_ECHO_STRENGTH))})
            members += 1
        lat, lon = offset_latlon(ORIGIN_LAT, ORIGIN_LON, ce, cn)
        schools.append({"school": f"S{index + 1}", "associated_target": net["id"],
                        "latitude": round(lat, 8), "longitude": round(lon, 8),
                        "fish": members, "centre_depth_m": round(centre_depth, 2),
                        "spread_m": 1.2})

    background = 0
    while background < max(20, pings // 25):
        ping = int(rng.integers(0, pings))
        cross = float(rng.choice([-1.0, 1.0])) * float(rng.uniform(2.0, 14.0))
        if (window[0] - 10 <= along[ping] <= window[1] + 10) and cross * side > 0:
            continue                                     # keep T5's aggregation exact
        fe, fn, water = place(ping, 0.0, cross)
        fish.append({"east": fe, "north": fn,
                     "depth": float(rng.uniform(SENSOR_DEPTH_M + 1.0, water - 0.5)),
                     "strength": float(rng.uniform(*FISH_ECHO_STRENGTH))})
        background += 1
    schools.append({"school": "background", "associated_target": None,
                    "fish": background, "note": "sparse single fish, both sides, outside "
                    "the T5 aggregation window"})
    return fish, schools


def _render(track: dict, seabed: Seabed, fish: list[dict], samples: int, rng):
    """Port and starboard sample arrays, shape (pings, samples), float counts."""
    import numpy as np

    pings = len(track["t"])
    dr = SLANT_RANGE_M / samples
    r = np.arange(samples) * dr                                  # sample k at k * dr
    altitude_all = _altitude(track)
    fish_e = np.array([f["east"] for f in fish])
    fish_n = np.array([f["north"] for f in fish])
    fish_z = np.array([f["depth"] for f in fish])
    fish_s = np.array([f["strength"] for f in fish])
    out = {}
    for side, sign in (("port", -1.0), ("stbd", 1.0)):
        data = np.empty((pings, samples), dtype=np.float32)
        chunk = 200
        for start in range(0, pings, chunk):
            sl = slice(start, min(start + chunk, pings))
            a = altitude_all[sl][:, None]
            hr = np.radians(track["heading"][sl])[:, None]
            pitch = np.radians(track["pitch"][sl])[:, None]
            roll = np.radians(track["roll"][sl])[:, None]
            R = r[None, :]
            wet = R > a
            g = np.sqrt(np.clip(R * R - a * a, 1e-6, None))
            shift = R * np.sin(pitch)                             # footprint fore/aft
            E = track["east"][sl][:, None] + sign * g * np.cos(hr) + shift * np.sin(hr)
            N = track["north"][sl][:, None] - sign * g * np.sin(hr) + shift * np.cos(hr)
            height, refl = seabed.sample(E, N)

            depression = (a - height) / g
            depression = np.where(wet, depression, np.inf)
            prev_min = np.minimum.accumulate(
                np.concatenate([np.full((depression.shape[0], 1), np.inf), depression[:, :-1]],
                               axis=1), axis=1)
            visible = depression <= prev_min + 1e-9
            slope = np.gradient(height, axis=1) / dr
            grazing = np.arctan2(a - height, g) + np.arctan(slope)
            intensity = refl * np.clip(np.sin(grazing), 0.0, None) ** 1.2 + 0.02
            intensity = np.where(visible, intensity, 0.018)
            intensity *= 1.0 + 0.3 * (g / SLANT_RANGE_M)           # residual TVG slope
            nadir = 2.0 * np.exp(-((R - a) / 0.35) ** 2)
            intensity = np.where(wet, intensity + nadir, 0.012 + 0.004 * np.sin(R))

            # Fish: echo at the true slant range, weighted by the fore/aft footprint.
            if len(fish):
                hrs = np.radians(track["heading"][sl])
                de = fish_e[None, :] - track["east"][sl][:, None]
                dn = fish_n[None, :] - track["north"][sl][:, None]
                fwd = de * np.sin(hrs)[:, None] + dn * np.cos(hrs)[:, None]
                crs = de * np.cos(hrs)[:, None] - dn * np.sin(hrs)[:, None]
                sensor_depth = SENSOR_DEPTH_M - track["heave"][sl]
                vertical = fish_z[None, :] - sensor_depth[:, None]
                hit = (np.abs(fwd) < 3 * FISH_FOOTPRINT_M) & (sign * crs > 0) & (vertical > 0)
                for pi, fi in zip(*np.nonzero(hit)):
                    slant = math.hypot(crs[pi, fi], vertical[pi, fi])
                    if slant >= SLANT_RANGE_M:
                        continue
                    k = int(slant / dr)
                    lo, hi = max(k - 4, 0), min(k + 5, samples)
                    weight = math.exp(-(fwd[pi, fi] / FISH_FOOTPRINT_M) ** 2)
                    intensity[pi, lo:hi] += fish_s[fi] * weight * np.exp(
                        -((r[lo:hi] - slant) / FISH_ECHO_WIDTH_M) ** 2)

            intensity *= np.exp(sign * roll * 1.5)                 # roll imbalance
            intensity *= np.exp(-((np.degrees(pitch) / 6.0) ** 2) * 0.7)
            speckle = rng.rayleigh(scale=1.0 / math.sqrt(math.pi / 2.0), size=intensity.shape)
            data[sl] = intensity * speckle * COUNTS_SCALE
        out[side] = data
    return out


def _parse_start(value: Any) -> datetime:
    if value is None:
        return START_TIME
    if isinstance(value, datetime):
        parsed = value
    else:
        parsed = datetime.fromisoformat(str(value).strip().replace("Z", "+00:00"))
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc)


def make_synthetic_xtf(out_dir, *, pings: int = 1600, samples: int = 500, seed: int = 57,
                       name: str = "SYNTHETIC_mannar_line01", start_time: Any = None,
                       scenario: str = "baseline") -> tuple[Path, Path]:
    """Write {name}.xtf and {name}.truth.json. Returns both paths.

    start_time: first ping time (datetime or ISO string, UTC when naive);
    default START_TIME. scenario: "baseline" (default) or "repeat" (see the
    module docstring).
    """
    import numpy as np
    import pyxtf

    if scenario not in SCENARIOS:
        raise ValueError(f"unknown scenario {scenario!r}; choose from {SCENARIOS}")
    start = _parse_start(start_time)
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(seed)

    track = _track(pings, PING_INTERVAL_S)
    layout = _layout(pings, scenario, track)
    a0, a1 = layout["attitude"]
    seg = slice(a0, a1)
    ts = track["t"][seg] - track["t"][a0]
    track["pitch"][seg] += 9.0 * np.sin(2 * np.pi * ts / 3.1)
    track["roll"][seg] += 14.0 * np.sin(2 * np.pi * ts / 2.6)
    track["heave"][seg] += 0.8 * np.sin(2 * np.pi * ts / 3.0)

    seabed = Seabed(track, layout, rng)
    # A second recording of the same seabed has its own speckle and its own
    # passing fish; the baseline keeps the single stream it always used.
    noise_rng = rng if scenario == "baseline" else np.random.default_rng([seed, 2])
    fish, schools = _fish(track, layout, seabed, noise_rng)
    data = _render(track, seabed, fish, samples, noise_rng)
    altitude = _altitude(track)
    g0, g1 = layout["gap"]
    e0, e1 = layout["empty"]
    data["port"][e0:e1] = 0.0
    data["stbd"][e0:e1] = 0.0

    header = pyxtf.XTFFileHeader()
    header.SonarName = b"SYNTH-SSS-400"
    header.NoteString = SYNTHETIC_NOTE.encode("ascii")[:64]
    header.ThisFileName = f"{name}.xtf".encode("ascii")[:64]
    header.NavUnits = 3                                            # latitude/longitude
    header.NumberOfSonarChannels = 2
    for index, (kind, label) in enumerate(((1, b"PORT"), (2, b"STBD"))):
        info = header.ChanInfo[index]
        info.TypeOfChannel = kind
        info.SubChannelNumber = index
        info.BytesPerSample = 2
        info.SampleFormat = 3                                      # 2-byte integer
        info.ChannelName = label
        info.Frequency = 400.0
        info.HorizBeamAngle = 0.5
        info.TiltAngle = 20.0
        info.BeamWidth = 50.0

    notes = pyxtf.XTFNotesHeader()
    notes.NumBytesThisRecord = 256
    notes.Year, notes.Month, notes.Day = start.year, start.month, start.day
    notes.NotesText = (SYNTHETIC_NOTE + ". Ground truth in the .truth.json beside this "
                       "file. No sonar was deployed.").encode("ascii")[:200]

    xtf_path = out_dir / f"{name}.xtf"
    written = 0
    with xtf_path.open("wb") as handle:
        handle.write(bytes(header))
        handle.write(bytes(notes))
        for i in range(pings):
            if g0 <= i < g1:
                continue                                           # the dropout: never recorded
            when = start + timedelta(seconds=float(track["t"][i]))
            lat, lon = offset_latlon(ORIGIN_LAT, ORIGIN_LON, float(track["east"][i]),
                                     float(track["north"][i]))
            ping = pyxtf.XTFPingHeader()
            ping.HeaderType = 0
            ping.NumChansToFollow = 2
            ping.NumBytesThisRecord = 256 + 2 * (64 + samples * 2)
            ping.Year, ping.Month, ping.Day = when.year, when.month, when.day
            ping.Hour, ping.Minute, ping.Second = when.hour, when.minute, when.second
            ping.HSeconds = when.microsecond // 10000
            ping.JulianDay = when.timetuple().tm_yday
            ping.PingNumber = i
            ping.SoundVelocity = 750.0
            ping.SensorXcoordinate = lon
            ping.SensorYcoordinate = lat
            ping.ShipXcoordinate = lon
            ping.ShipYcoordinate = lat
            ping.SensorSpeed = float(track["speed"][i]) * KNOTS_PER_MPS
            ping.ShipSpeed = ping.SensorSpeed
            ping.SensorPrimaryAltitude = float(altitude[i])
            ping.SensorDepth = float(SENSOR_DEPTH_M - track["heave"][i])
            ping.SensorPitch = float(track["pitch"][i])
            ping.SensorRoll = float(track["roll"][i])
            ping.SensorHeading = float(track["heading"][i])
            ping.Heave = float(track["heave"][i])
            channels, arrays = [], []
            for c, side in enumerate(("port", "stbd")):
                chan = pyxtf.XTFPingChanHeader()
                chan.ChannelNumber = c
                chan.SlantRange = SLANT_RANGE_M
                chan.NumSamples = samples
                chan.SecondsPerPing = PING_INTERVAL_S
                chan.TimeDelay = 0.0
                chan.TimeDuration = 2 * SLANT_RANGE_M / 1500.0
                chan.Frequency = 400
                channels.append(chan)
                arrays.append(np.clip(data[side][i], 0, 65535).astype("<u2"))
            ping.ping_chan_headers = channels
            ping.data = arrays
            handle.write(ping.to_bytes())
            written += 1

    def when_iso(index: int) -> str:
        return (start + timedelta(seconds=float(track["t"][index]))).isoformat(
            timespec="milliseconds")

    truth = {
        "synthetic": True,
        "warning": "SYNTHETIC GROUND TRUTH. Generated by tools/make_synthetic_xtf.py. "
                   "No sonar was deployed and none of these objects or fish exists.",
        "generator": "tools/make_synthetic_xtf.py",
        "seed": seed,
        "scenario": scenario,
        "xtf_file": xtf_path.name,
        "area": "Gulf of Mannar, near the Marine National Park islands (synthetic seabed)",
        "origin": {"latitude": ORIGIN_LAT, "longitude": ORIGIN_LON,
                   "note": "local east/north metres are measured from here"},
        "sonar": {"slant_range_m": SLANT_RANGE_M, "samples_per_channel": samples,
                  "slant_m_per_sample": SLANT_RANGE_M / samples,
                  "ping_interval_s": PING_INTERVAL_S, "frequency_khz": 400,
                  "sample_format": "uint16, sample k at k * SlantRange / NumSamples"},
        "track": {"pings_simulated": pings, "pings_written": written,
                  "start_time": when_iso(0), "end_time": when_iso(pings - 1),
                  "length_m": round(float(track["along"][-1]), 2),
                  "sensor_depth_m": SENSOR_DEPTH_M,
                  "water_depth_m": [round(float(track["depth"].min()), 2),
                                    round(float(track["depth"].max()), 2)],
                  "altitude_m": [round(float(altitude.min()), 2),
                                 round(float(altitude.max()), 2)],
                  "speed_mps": [round(float(track["speed"].min()), 3),
                                round(float(track["speed"].max()), 3)],
                  "heading_deg": [round(float(track["heading"].min()), 2),
                                  round(float(track["heading"].max()), 2)],
                  "position_recorded": "SensorX/Ycoordinate = true towfish position "
                                       "(no layback)"},
        "injected": {
            "attitude_excursion": {"ping_start": a0, "ping_end": a1 - 1,
                                   "time_start": when_iso(a0), "time_end": when_iso(a1 - 1),
                                   "pitch_amplitude_deg": 9.0, "roll_amplitude_deg": 14.0,
                                   "heave_amplitude_m": 0.8},
            "dropout_time_gap": {"ping_start": g0, "ping_end": g1 - 1,
                                 "time_start": when_iso(g0), "time_end": when_iso(g1 - 1),
                                 "pings_missing": g1 - g0,
                                 "distance_m": round(float(track["along"][g1] - track["along"][g0]), 2)},
            "empty_pings": {"ping_start": e0, "ping_end": e1 - 1,
                            "time_start": when_iso(e0), "time_end": when_iso(e1 - 1),
                            "note": "written with all-zero samples"},
        },
        "targets": seabed.truth,
        "scenario_changes": _changes_with_positions(layout["scenario_changes"], seabed.truth),
        "fish": {"total": len(fish), "schools": schools,
                 "aggregation_target": layout["aggregation_net"],
                 "control_target": layout["control_net"],
                 "echo_model": "point scatterer at true slant range, Gaussian fore/aft "
                               f"footprint sigma {FISH_FOOTPRINT_M} m, echo width "
                               f"{FISH_ECHO_WIDTH_M} m"},
        "not_modelled": ["layover", "multipath", "refraction", "layback", "yaw/crab",
                         "fish shadows"],
    }
    truth_path = out_dir / f"{name}.truth.json"
    truth_path.write_text(json.dumps(truth, indent=2), encoding="utf-8")
    return xtf_path, truth_path


def _changes_with_positions(changes: list[dict], truth: list[dict]) -> list[dict]:
    """Scenario changes, with the new position of every target still present."""
    by_id = {t["id"]: t for t in truth}
    out = []
    for change in changes:
        entry = dict(change)
        if change["id"] in by_id:
            entry["latitude"] = by_id[change["id"]]["latitude"]
            entry["longitude"] = by_id[change["id"]]["longitude"]
        out.append(entry)
    return out


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0],
                                     formatter_class=argparse.RawDescriptionHelpFormatter,
                                     epilog=__doc__)
    parser.add_argument("--out", default=str(ROOT / "survey_hazard_map" / "samples" / "synthetic_xtf"))
    parser.add_argument("--pings", type=int, default=1600)
    parser.add_argument("--samples", type=int, default=500)
    parser.add_argument("--seed", type=int, default=57)
    parser.add_argument("--name", default="SYNTHETIC_mannar_line01")
    parser.add_argument("--start-time", default=None,
                        help=f"first ping time, ISO-8601 (UTC if no offset); default "
                             f"{START_TIME.isoformat()}")
    parser.add_argument("--scenario", choices=SCENARIOS, default="baseline",
                        help="baseline line, or the same line re-surveyed with changes")
    args = parser.parse_args(argv)
    xtf_path, truth_path = make_synthetic_xtf(args.out, pings=args.pings, samples=args.samples,
                                              seed=args.seed, name=args.name,
                                              start_time=args.start_time, scenario=args.scenario)
    size = xtf_path.stat().st_size / 1e6
    print(f"SYNTHETIC XTF written: {xtf_path} ({size:.1f} MB)")
    print(f"ground truth:          {truth_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
