/**
 * Where the survey API is, and every label and colour this feature uses.
 *
 * Same rule the assistant follows: nothing else in this directory knows a URL
 * or hard-codes a word the operator reads. Change it here and the whole page
 * follows.
 */

const fromEnv = import.meta.env.VITE_API_BASE_URL

export const surveyConfig = {
  /** Base URL of the FastAPI backend. Override with VITE_API_BASE_URL. */
  apiBaseUrl: (fromEnv && fromEnv.trim()) || "http://127.0.0.1:8000",

  endpoints: {
    surveys: "/survey",
    export: (id) => `/survey/${encodeURIComponent(id)}/export`,
    map: (id) => `/survey/${encodeURIComponent(id)}/map`,
    actions: (id) => `/survey/${encodeURIComponent(id)}/actions.csv`,
    replay: (id) => `/survey/${encodeURIComponent(id)}/replay`,
    coverage: (id) => `/survey/${encodeURIComponent(id)}/coverage`,
    relook: (id, format) => `/survey/${encodeURIComponent(id)}/relook.${format}`,
    ghosttrace: (id) => `/ghosttrace/${encodeURIComponent(id)}`,
  },

  /** Optional background map. Everything drawn on top of it works without it. */
  basemap: {
    url: "https://tile.openstreetmap.org/{z}/{x}/{y}.png",
    attribution: "&copy; OpenStreetMap contributors",
    maxNativeZoom: 19,
  },
}

/**
 * Colours drawn by Leaflet. SVG presentation attributes cannot read CSS custom
 * properties, so these are the dashboard palette's values written out.
 */
export const mapColors = {
  track: "#087f9c",
  trackFuture: "#94a3b8",
  degraded: "#dc2626",
  swath: "#087f9c",
  swathDegraded: "#dc2626",
  sweep: "#0ea5c6",
  imaged: "#0d9488",
  nadir: "#64748b",
  hull: "#64748b",
  gap: "#dc2626",
  relook: "#7c3aed",
  tier: { critical: "#dc2626", medium: "#d97706", low: "#16a34a" },
  tierFallback: "#64748b",
  filtered: "#64748b",
}

export const replaySpeeds = [1, 10, 60]

/**
 * Severity tiers, mapped onto the dashboard's existing palette variables.
 *
 * The engine decides which tier a thing is in and this only decides how it
 * looks, exactly as the backend's own severity table is looked up rather than
 * inferred. A tier the engine adds later that is not listed here renders in
 * the neutral fallback instead of guessing a colour, because picking a colour
 * for an unknown risk level is itself a claim.
 */
export const tierStyle = {
  critical: { label: "Critical", color: "var(--danger)", tint: "#fdeaea" },
  medium: { label: "Medium", color: "var(--warning)", tint: "#fdf3e7" },
  low: { label: "Low", color: "var(--success)", tint: "#eaf6ef" },
}

export const tierFallback = { label: "Unclassified", color: "var(--muted)", tint: "#eef2f6" }

export function styleForTier(tier) {
  return tierStyle[tier] || tierFallback
}

/** Priority filter options. Derived from nothing; they are plain cut-offs. */
export const priorityOptions = [
  { value: "all", label: "All" },
  { value: "5", label: "Top 5" },
  { value: "10", label: "Top 10" },
  { value: "20", label: "Top 20" },
]

export const copy = {
  title: "Survey Hazard Intelligence",
  subtitle: "Where the hazards are, and which one to look at first",
  relativeMode: "Relative survey coordinates",
  relativeNote:
    "This survey has no navigation. Positions are pixel offsets inside the sonar " +
    "strip, not geographic coordinates. Nothing on this page is a GPS position.",
  geoMode: "Geo-referenced",
  geoNote:
    "Positions are interpolated from the survey's navigation. Relative pixel " +
    "coordinates are kept alongside them.",
  demoBanner: "Synthetic demo data",
  demoNote:
    "Every contact in this survey was generated by the demo script. No sonar was " +
    "recorded and nothing here is evidence of anything.",
  noSurveys:
    "No processed surveys yet. Run run_survey.py or demo_survey.py and the " +
    "results appear here.",
  noHotspots:
    "The detector returned nothing above the confidence threshold for this " +
    "survey. It ran; there is simply nothing to rank.",
  noMatch: "No hotspot matches these filters.",
  askAssistant: "Ask the assistant about this hazard",
  filteredChip: "filtered",
  withheldChip: "withheld",
  filteredTitle: "Filtered false positives",
  filteredNote:
    "Verification marked these detections as likely false positives: acoustic " +
    "artefacts, shadows, clutter or degraded rows rather than objects. They are not " +
    "deleted. They stay in export.json and report.csv with their reasons, and are " +
    "left out of every hotspot, which is why they are listed here on their own.",
  filteredNone: "Verification ran on this survey and filtered nothing.",
  filteredShow: (count) => `Show ${count} filtered detection${count === 1 ? "" : "s"}`,
  filteredHide: "Hide filtered detections",
  notVerified: "not in this export",
  notVerifiedNote: "export predates verification",
  hardReasons: {
    nadir_zone: "nadir / water-column artefact",
    natural_shadow: "natural shadow or depression",
    rock_clutter: "rock field or natural clutter",
    dropout: "degraded sonar rows (dropout or motion)",
  },
  replayTitle: "Mission replay",
  replayNote:
    "The survey as it was flown, in ping-time order, from the navigation sidecar: the " +
    "towfish track, the swath it swept, and each contact as the sonar passed it. Red is " +
    "degraded sonar (dropout, attitude or interpolated rows).",
  replayUnavailable:
    "No mission replay for this survey. It has no per-ping navigation, so there is no " +
    "track, no ping time and no swath to replay; nothing is reconstructed in their place.",
  coverageTitle: "Coverage and blind spots",
  coverageNote:
    "Which seabed the sonar actually imaged. Degraded rows and the nadir strip under the " +
    "towfish are not counted as imaged. Re-look lines are a planning heuristic, not a " +
    "navigation procedure: check depth, traffic and turning circle before running one.",
  coverageUnavailable:
    "No coverage analysis for this survey. Without a towfish track, heading and altitude " +
    "there is no seabed footprint to compute, so none is shown.",
  reportButton: "Survey report",
  synthetic: "Synthetic",
  disclaimer:
    "Severity weights and recommended actions are a configurable heuristic " +
    "chosen for this project. They are not Navy, Coast Guard, NOAA or IMO " +
    "procedure and carry no authority.",
}
