"""Who should be told, and what should the message say?

A detection nobody reports rescues nothing. This module drafts one alert per
target: a subject, a plain-text body a survey lead can paste into an email or
a radio log, the authorities the message is for, and the corpus citations for
every authority it names.

THE ONE RULE: NO INVENTED CONTACTS
    An authority is named only when a document in kb/ names it for that
    situation, and the name is checked against the document text at run time
    (whitespace-normalised, case-insensitive). If the kb changes and the name
    disappears, the entry degrades to "authority not in corpus" by itself.
    No phone number, email address or URL that is not in the corpus is ever
    written. Where the corpus is silent - and for ghost gear it largely is -
    the alert says so explicitly, because an honest gap sends the operator to
    find the right office, while a plausible invented one sends the report to
    the wrong desk.

WHAT THE CORPUS ACTUALLY COVERS (kb/, as of this writing)
    * kb/reporting-authorities-india.md names the Indian Coast Guard Maritime
      Rescue Coordination Centre as the reporting channel for a discharge or
      probable discharge of oil / hazardous and noxious substances. It is
      offered ONLY for drums and containers (possible contents), and its role
      text says it is not the channel for the gear itself.
    * The same document says a hazard to navigation is broadcast by "the
      authority", and kb/unidentified-object-protocol.md says to call
      "emergency services" for an object of unknown nature - but no Indian
      office for navigational warnings, fisheries, marine protected areas or
      wildlife is named anywhere. Those situations get "authority not in
      corpus" with the role that is missing.

GENERATED BY
    "template" (default, offline, deterministic) or "assistant" when
    GHOSTTRACE_USE_ASSISTANT=1: the template facts are sent through the
    existing grounded assistant (rag_assistant.chat.answer) with a timeout. Any
    failure, refusal or ungrounded answer falls back to the template and the
    reason is recorded in `basis`. The authority list always comes from the
    deterministic corpus check, never from the model.
"""

from __future__ import annotations

import concurrent.futures
import re
from functools import lru_cache
from pathlib import Path
from typing import Any

from ghosttrace import config_core as cfg
from ghosttrace.changes import class_family, class_matches

REPO_ROOT = Path(__file__).resolve().parent.parent

# situation -> candidate authorities. `name` must occur in `doc` for the entry
# to be used. Each carries the section it is grounded in.
AUTHORITY_REGISTRY: dict[str, list[dict[str, str]]] = {
    "possible_pollution": [{
        "name": "Indian Coast Guard Maritime Rescue Coordination Centre",
        "doc": "reporting-authorities-india.md",
        "section": "Pollution: the Indian obligation, verbatim in substance",
        "role": ("pollution reporting channel, ONLY if a discharge or probable discharge of oil "
                 "or a hazardous and noxious substance from the object is observed; not the "
                 "channel for the object itself"),
    }],
    "unknown_contents": [{
        "name": "emergency services",
        "doc": "unidentified-object-protocol.md",
        "section": "Immediate actions",
        "role": ("first call for a drum, cylinder or pressure vessel of unknown contents, which "
                 "the corpus treats as an unidentified object, not debris"),
    }],
    "unidentified_object": [{
        "name": "emergency services",
        "doc": "unidentified-object-protocol.md",
        "section": "Immediate actions",
        "role": ("first call for an object that cannot be positively identified, which the corpus "
                 "treats as potentially explosive: do not approach, dive on or recover it"),
    }],
    # Filled from kb/ghost-gear-reporting-india.md, which was written from the
    # 2024 National Action Plan, the FAO gear-marking guidelines, the National
    # Hydrographic Office's own pages, a Tamil Nadu G.O. and Odisha forest
    # department records. Every role states the limit its source sets: none of
    # these offices is described as a ghost-gear reporting desk, and the
    # National Action Plan lists a lost-gear reporting mechanism as "In
    # preparation".
    "navigation_hazard": [{
        "name": "National Hydrographic Office",
        "doc": "ghost-gear-reporting-india.md",
        "section": "Reporting a danger to navigation to the National Hydrographic Office",
        "role": ("coordinator of NAVAREA VIII; a danger to navigation observed at sea is "
                 "reported through its Abridged Hydrographic Note"),
    }],
    "fisheries": [{
        "name": "State Fisheries Departments",
        "doc": "ghost-gear-reporting-india.md",
        "section": "Lost or found fishing gear: the fisheries authorities",
        "role": ("fisheries is a state subject; the sources establish no lost-gear reporting "
                 "channel yet (the National Action Plan lists one as 'In preparation')"),
    }, {
        "name": "Fishery Survey of India",
        "doc": "ghost-gear-reporting-india.md",
        "section": "Retrieval already under way",
        "role": ("its survey vessels are stated to be retrieving abandoned, lost or discarded "
                 "fishing gear; a candidate for recovery, not a designated reporting desk"),
    }],
    # Location-scoped: a Gahirmatha net must not be sent to the Gulf of Mannar
    # warden. `habitat_match` substrings are checked against the names of the
    # habitat the target sits in, is near, or is forecast to drift into.
    "protected_habitat": [{
        "name": "Wildlife Warden, Ramanathapuram",
        "doc": "ghost-gear-reporting-india.md",
        "section": "Ghost gear inside or near the Gulf of Mannar Marine National Park",
        "habitat_match": ("gulf of mannar", "mannar"),
        "role": ("listed by the Ramanathapuram forest department, which oversees the Gulf of "
                 "Mannar Marine National Park; manager of the area, not a designated ghost-gear desk"),
    }, {
        "name": "District Forest Officer, Thanjavur and Pudukkottai",
        "doc": "ghost-gear-reporting-india.md",
        "section": "Ghost gear in the Palk Bay Dugong Conservation Reserve",
        "habitat_match": ("palk bay", "dugong"),
        "role": ("an addressee of the G.O. declaring the Dugong Conservation Reserve; the order "
                 "names no managing authority, so this is the nearest named forest office"),
    }, {
        "name": "Mangrove Forest Division (Wildlife), Rajnagar",
        "doc": "ghost-gear-reporting-india.md",
        "section": "Ghost gear near Gahirmatha and Odisha sea turtle nesting areas",
        "habitat_match": ("gahirmatha",),
        "role": ("forest division recorded for Gahirmatha Marine Wildlife Sanctuary; manager of "
                 "the area, not a designated ghost-gear desk"),
    }, {
        "name": "PCCF (Wildlife) & Chief Wildlife Warden, Odisha",
        "doc": "ghost-gear-reporting-india.md",
        "section": "Ghost gear near Gahirmatha and Odisha sea turtle nesting areas",
        "habitat_match": ("gahirmatha", "rushikulya", "devi", "odisha"),
        "role": ("chairs Odisha's sea turtle coordination committee, whose SOP must address "
                 "entanglement in nets"),
    }],
}

MISSING_ROLE: dict[str, str] = {
    "navigation_hazard": ("Indian authority that issues navigational warnings for a hazard to "
                          "navigation (kb/reporting-authorities-india.md says the authority, not "
                          "the detecting vessel, broadcasts it, but names no Indian office)"),
    "fisheries": "fisheries authority responsible for derelict or abandoned fishing gear",
    "protected_habitat": ("marine protected area / wildlife authority for the habitat near or "
                          "downstream of the target"),
}

REPORT_FIELDS_CITATION = {"doc": "kb/reporting-authorities-india.md",
                          "section": "What a report carries"}


@lru_cache(maxsize=16)
def _kb_text(kb_dir: str, doc: str) -> str:
    try:
        return (Path(kb_dir) / doc).read_text(encoding="utf-8")
    except OSError:
        return ""


def _front_matter(text: str) -> dict[str, str]:
    m = re.match(r"^---\n(.*?)\n---\n", text, flags=re.S)
    out = {}
    if m:
        for line in m.group(1).splitlines():
            if ":" in line:
                k, v = line.split(":", 1)
                out[k.strip()] = v.strip()
    return out


def _squash(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip().lower()


def kb_dir_path(kb_dir: Any = None) -> str:
    p = Path(kb_dir or cfg.KB_DIR)
    return str(p if p.is_absolute() else REPO_ROOT / p)


def name_in_corpus(name: str, doc: str, kb_dir: Any = None) -> bool:
    return _squash(name) in _squash(_kb_text(kb_dir_path(kb_dir), doc))


def situations_for(target: dict[str, Any]) -> list[str]:
    cls = target.get("object_class")
    out = []
    if class_family(cls) == cfg.ACTIVE_GEAR_FAMILY:
        out.append("fisheries")
    if class_family(cls) == "unknown":
        out.append("unidentified_object")
    if any(class_matches(cls, k) for k in ("drum", "container", "barrel", "cylinder")):
        out += ["unknown_contents", "possible_pollution"]
    habitat = target.get("habitat") or {}
    drift = target.get("drift") or {}
    near = False
    if habitat.get("available", True):
        if habitat.get("inside"):
            near = True
        for n in habitat.get("nearest") or []:
            if isinstance(n.get("distance_m"), (int, float)) and n["distance_m"] <= cfg.NEAR_HABITAT_M:
                near = True
        if isinstance(habitat.get("score"), (int, float)) and habitat["score"] >= cfg.NEAR_HABITAT_SCORE:
            near = True
    if drift.get("available", True):
        for i in drift.get("impacts") or []:
            kind = f"{i.get('kind')} {i.get('name')}".lower().replace(" ", "-")
            if (i.get("probability") or 0) > 0 and any(k in kind for k in cfg.SENSITIVE_IMPACT_KINDS):
                near = True
    # A seabed net the "if refloated" scenario carries into a protected area is
    # a net that area's manager should hear about, even though the scenario
    # never raises priority. Held to a higher bar than the forecast.
    for i in _scenario_impacts(target):
        kind = f"{i.get('kind')} {i.get('name')}".lower().replace(" ", "-")
        if (i.get("probability") or 0) >= cfg.SCENARIO_NOTIFY_PROBABILITY and \
                any(k in kind for k in cfg.SENSITIVE_IMPACT_KINDS):
            near = True
    if near:
        out.append("protected_habitat")
    level = str(((target.get("people") or {}).get("propeller_hazard") or {}).get("level") or "").lower()
    if level in cfg.PROPELLER_HAZARD_LEVELS:
        out.append("navigation_hazard")
    return out


def _habitat_names(target: dict[str, Any]) -> str:
    """Every habitat name the target is inside, near, or forecast to reach, lowercased.

    Used only to pick which location-scoped office an alert names. A target
    with no habitat context matches none of them and the alert says the
    authority is not in the corpus, rather than defaulting to some park.
    """
    habitat = target.get("habitat") or {}
    drift = target.get("drift") or {}
    names: list[str] = []
    if habitat.get("available", True):
        for item in habitat.get("inside") or []:
            names.append(str(item.get("name") if isinstance(item, dict) else item))
        names += [str(n.get("name") or "") for n in habitat.get("nearest") or []]
    if drift.get("available", True):
        names += [str(i.get("name") or "") for i in drift.get("impacts") or []
                  if (i.get("probability") or 0) > 0]
    names += [str(i.get("name") or "") for i in _scenario_impacts(target)
              if (i.get("probability") or 0) >= cfg.SCENARIO_NOTIFY_PROBABILITY]
    return " | ".join(names).lower()


def _scenario_impacts(target: dict[str, Any]) -> list[dict[str, Any]]:
    """Impacts of the "if refloated" drift scenario, or none."""
    scenario = (target.get("drift_scenarios") or {}).get("if_refloated") or {}
    if scenario.get("available", True) is False:
        return []
    return [i for i in scenario.get("impacts") or [] if isinstance(i, dict)]


def authorities_for(target: dict[str, Any], kb_dir: Any = None
                    ) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    """(authorities, citations). Names only from the corpus; gaps stated."""
    kbd = kb_dir_path(kb_dir)
    authorities: list[dict[str, Any]] = []
    citations: list[dict[str, Any]] = []
    places = _habitat_names(target)
    for situation in situations_for(target):
        found = False
        for entry in AUTHORITY_REGISTRY.get(situation, []):
            text = _kb_text(kbd, entry["doc"])
            if not name_in_corpus(entry["name"], entry["doc"], kbd):
                continue
            match = entry.get("habitat_match")
            if match and not any(m in places for m in match):
                continue
            fm = _front_matter(text)
            authorities.append({
                "name": entry["name"], "role": entry["role"], "situation": situation,
                "contact_basis": (f"named in kb/{entry['doc']} (section '{entry['section']}'); "
                                  "the corpus gives no phone number, email or address for it, so "
                                  "none is given here"),
            })
            citations.append({"doc": f"kb/{entry['doc']}", "section": entry["section"],
                              "title": fm.get("title"), "source_url": fm.get("source_url"),
                              "status": fm.get("status")})
            found = True
        if not found:
            role = MISSING_ROLE.get(situation) or f"authority for situation '{situation}'"
            authorities.append({
                "name": cfg.NOT_IN_CORPUS, "role": role, "situation": situation,
                "contact_basis": ("no document in kb/ names this authority; add a verified source "
                                  "to the corpus rather than guessing a contact"),
            })
    if authorities:
        fm = _front_matter(_kb_text(kbd, "reporting-authorities-india.md"))
        if fm:
            citations.append({**REPORT_FIELDS_CITATION, "title": fm.get("title"),
                              "source_url": fm.get("source_url"), "status": fm.get("status")})
    # De-duplicate citations, keep order.
    seen, uniq = set(), []
    for c in citations:
        key = (c["doc"], c["section"])
        if key not in seen:
            seen.add(key)
            uniq.append(c)
    return authorities, uniq


# --- template -------------------------------------------------------------------------

def _fmt_pos(t: dict[str, Any]) -> str:
    if t.get("latitude") is None or t.get("longitude") is None:
        return "position unavailable"
    return f"{float(t['latitude']):.5f}, {float(t['longitude']):.5f}"


def _source_name(src: Any) -> str:
    if isinstance(src, dict):
        return str(src.get("name") or "source not named")
    return str(src) if src else "source not stated"


def _lines(t: dict[str, Any], survey_id: str, demo: bool, synthetic: bool) -> list[str]:
    cls = t.get("object_class")
    lines = []
    if demo or synthetic:
        lines.append("SYNTHETIC / DEMO DATA - this is not a real detection and must not be sent.")
    lines.append("AUTOMATED DETECTION - VERIFY BEFORE ACTION.")
    pct = t.get("confidence_pct")
    lines.append(f"What: side-scan sonar contact classified '{cls}'"
                 + (f", confidence {pct:.0f}% ({t.get('confidence_basis')})." if isinstance(pct, (int, float))
                    else ", confidence not recorded."))
    if t.get("latitude") is None:
        lines.append("Where: position unavailable (survey not georeferenced).")
    else:
        lines.append(f"Where: {_fmt_pos(t)} (decimal degrees, WGS84 as recorded by the survey "
                     "navigation; accuracy not estimated).")
    dims = t.get("dimensions")
    if isinstance(dims, dict) and dims.get("length_m") is not None:
        parts = [f"{dims.get(k):.1f} m" for k in ("length_m", "width_m", "height_m")
                 if isinstance(dims.get(k), (int, float))]
        lines.append("Size: " + " x ".join(parts) + " (length x width x height as measured).")
    else:
        lines.append("Size: not measured.")

    a = t.get("activity") or {}
    if a.get("available"):
        ev = a.get("evidence") or {}
        lines.append(f"Water-column activity: {a.get('level')} (score {a.get('score')}; "
                     f"{ev.get('echo_clusters_near')} echo clusters within {ev.get('window_m')} m "
                     f"vs {ev.get('background_clusters_per_window')} per control window; may be "
                     "fish, bubbles or sediment - not proof of entanglement).")
    else:
        lines.append(f"Water-column activity: not measured ({a.get('reason', 'unavailable')}).")

    h = t.get("habitat") or {}
    if h.get("available", True) and ("nearest" in h or "inside" in h):
        inside = [i.get("name") if isinstance(i, dict) else str(i) for i in h.get("inside") or []]
        if inside:
            lines.append("Habitat: inside " + ", ".join(str(x) for x in inside) + ".")
        nearest = sorted((n for n in h.get("nearest") or [] if isinstance(n.get("distance_m"), (int, float))),
                         key=lambda n: n["distance_m"])
        if nearest:
            n = nearest[0]
            lines.append(f"Nearest habitat: {n.get('name')} ({n.get('kind')}) at "
                         f"{n['distance_m'] / 1000:.2f} km"
                         + (f", bearing {n['bearing_deg']:.0f} deg" if isinstance(n.get("bearing_deg"), (int, float)) else "")
                         + f" (source: {_source_name(n.get('source'))}).")
        elif not inside:
            lines.append("Habitat: no mapped habitat layer near the target.")
    else:
        lines.append(f"Habitat: unavailable ({h.get('reason', 'no habitat stage')}).")

    d = t.get("drift") or {}
    if d.get("available", True) and isinstance(d.get("impacts"), list):
        mode = d.get("mode") or d.get("requested_mode")
        horizon = d.get("horizon_hours")
        impacts = sorted(d["impacts"], key=lambda i: -(i.get("probability") or 0))
        if impacts:
            i = impacts[0]
            arrival = i.get("first_arrival_hours")
            lines.append(f"Drift forecast ({mode}, {horizon} h): {100 * (i.get('probability') or 0):.0f}% "
                         f"chance of reaching {i.get('name')} ({i.get('kind')})"
                         + (f", first arrival about {arrival:.0f} h" if isinstance(arrival, (int, float)) else "")
                         + ".")
        else:
            lines.append(f"Drift forecast ({mode}, {horizon} h): no mapped habitat reached.")
        if isinstance(d.get("stranding_probability"), (int, float)):
            lines.append(f"Stranding probability: {100 * d['stranding_probability']:.0f}%.")
    else:
        lines.append(f"Drift forecast: unavailable ({d.get('reason', 'no drift stage')}).")

    scenario_impacts = sorted(_scenario_impacts(t), key=lambda i: -(i.get("probability") or 0))
    if scenario_impacts:
        i = scenario_impacts[0]
        arrival = i.get("first_arrival_hours")
        lines.append(f"Scenario, not a forecast -- if this net is lifted off the seabed: "
                     f"{100 * (i.get('probability') or 0):.0f}% chance of reaching {i.get('name')}"
                     + (f", first arrival about {arrival:.0f} h" if isinstance(arrival, (int, float)) else "")
                     + ".")

    p = t.get("people") or {}
    if p.get("available", True) and p.get("propeller_hazard"):
        ph = p["propeller_hazard"]
        reasons = "; ".join(str(r) for r in (ph.get("reasons") or [])[:3])
        lines.append(f"Propeller hazard: {ph.get('level')}" + (f" - {reasons}" if reasons else "") + ".")
        brief = p.get("diver_brief")
        if isinstance(brief, dict):
            text = brief.get("summary") or "; ".join(
                f"{k}: {v}" for k, v in brief.items() if isinstance(v, (str, int, float)))[:400]
            if text:
                lines.append(f"Diver notes: {text}.")
        elif isinstance(brief, str):
            lines.append(f"Diver notes: {brief}.")
    else:
        lines.append(f"Propeller / diver hazard: unavailable ({p.get('reason', 'no safety stage')}).")

    c = t.get("change") or {}
    if c.get("status"):
        moved = ""
        if c.get("moved_m") is not None:
            moved = (f", displacement {c['moved_m']} m (within positional uncertainty, not claimed as "
                     "movement)" if c["status"] == "persistent" else f", moved {c['moved_m']} m")
        if c.get("previous_survey_id"):
            moved += f" (compared with survey {c['previous_survey_id']})"
        lines.append(f"Change since previous survey: {c['status']}{moved}.")
    pr = t.get("priority") or {}
    if pr:
        lines.append(f"GhostTrace priority: {pr.get('tier')} (score {pr.get('score')}, rank "
                     f"{pr.get('rank')}; heuristic).")
    lines.append(f"Survey: {survey_id}. Detection: {t.get('detection_id')}.")
    lines.append("Still to be completed by the operator before sending (per kb/reporting-"
                 "authorities-india.md, 'What a report carries'): time of detection in UTC, "
                 "position datum and accuracy estimate, water and object depth, sensor settings, "
                 "vessel identity, operator, and the vessel's intentions.")
    return lines


def template_alert(target: dict[str, Any], *, survey_id: str, demo: bool = False,
                   synthetic: bool = False, kb_dir: Any = None) -> dict[str, Any]:
    authorities, citations = authorities_for(target, kb_dir)
    lines = _lines(target, survey_id, demo, synthetic)
    if authorities:
        lines.append("Report to:")
        for a in authorities:
            lines.append(f"  - {a['name']}: {a['role']}.")
    lines.append(cfg.ALERT_DISCLAIMER)
    tier = (target.get("priority") or {}).get("tier") or "unranked"
    prefix = "[SYNTHETIC] " if (demo or synthetic) else ""
    subject = (f"{prefix}GhostTrace {tier}: suspected {target.get('object_class')} at "
               f"{_fmt_pos(target)} (survey {survey_id})")
    return {"authorities": authorities, "subject": subject, "draft_text": "\n".join(lines),
            "generated_by": "template", "citations": citations,
            "basis": ("deterministic template from this target's GhostTrace fields; authorities "
                      "only where kb/ names them for the situation")}


def _assistant_answer(message: str, detection: dict[str, Any]) -> dict[str, Any]:
    import sys
    if str(REPO_ROOT) not in sys.path:
        sys.path.insert(0, str(REPO_ROOT))
    from rag_assistant.chat import answer  # noqa: WPS433 (optional dependency)
    return answer(message, detection=detection)


def draft_alert(target: dict[str, Any], *, survey_id: str, demo: bool = False,
                synthetic: bool = False, kb_dir: Any = None,
                use_assistant: bool | None = None, assistant_fn=None) -> dict[str, Any]:
    """Alert block for one target. Template unless the assistant is enabled and succeeds."""
    alert = template_alert(target, survey_id=survey_id, demo=demo, synthetic=synthetic, kb_dir=kb_dir)
    use = cfg.USE_ASSISTANT if use_assistant is None else use_assistant
    if not use:
        return alert
    fn = assistant_fn or _assistant_answer
    message = ("Using only the sources, draft a short report to the responsible authority about "
               "this side-scan sonar contact. Do not add any contact details that are not in the "
               "sources. Facts:\n" + alert["draft_text"])
    detection = {"object_class": target.get("object_class"),
                 "confidence": (target.get("confidence_pct") or 0) / 100.0}
    pool = concurrent.futures.ThreadPoolExecutor(max_workers=1)
    try:
        future = pool.submit(fn, message, detection)
        result = future.result(timeout=cfg.ASSISTANT_TIMEOUT_S)
    except concurrent.futures.TimeoutError:
        alert["basis"] += f"; assistant timed out after {cfg.ASSISTANT_TIMEOUT_S:g} s, template used"
        return alert
    except BaseException as exc:  # SystemExit from rag.py included
        alert["basis"] += f"; assistant failed ({type(exc).__name__}: {str(exc)[:160]}), template used"
        return alert
    finally:
        pool.shutdown(wait=False)
    text = (result or {}).get("answer")
    if not text or result.get("refusal") or not result.get("grounded", False):
        alert["basis"] += "; assistant answer was a refusal or not grounded, template used"
        return alert
    sources = [{k: s.get(k) for k in ("n", "title", "section", "doc_id", "authority", "status", "path")}
               for s in result.get("sources") or []]
    alert.update({
        "draft_text": text.rstrip() + "\n\n" + cfg.ALERT_DISCLAIMER,
        "generated_by": "assistant",
        "citations": alert["citations"] + [{"assistant_source": s} for s in sources],
        "basis": ("grounded assistant (rag_assistant.chat.answer) given the template facts; the authority "
                  "list is from the deterministic corpus check, not from the model"),
    })
    return alert
