#!/usr/bin/env python3
"""The GhostTrace demo surveys: a synthetic Gulf of Mannar line, surveyed twice.

    python3 tools/make_ghosttrace_demo.py        # both surveys under data/surveys/
    python3 tools/make_ghosttrace_demo.py --surveys-root DIR

writes
    demo-ghosttrace-mannar          line 01, recorded LINE01_START
    demo-ghosttrace-mannar-repeat   line 02, the same track re-surveyed
                                    REPEAT_DELAY later: net T5 moved ~40 m (still
                                    ghost-fishing), net T7 gone, a new net T8

GhostTrace runs on line 01 first and then on the repeat with the surveys root,
so its change stage compares the two: T5 "moved", T7 in
removed_since_previous, T8 "new". Survey order comes from the ping times in
the navigation sidecars, not from when the demo was built.

WHY THESE DATES
    Both lines, and each line's 240 h drift horizon, fall inside the bundled
    HYCOM current window (data/ghosttrace/manifest.json), so the forecast runs on
    the model's own currents for those dates with no time mapping. After
    re-fetching currents for a new window, move LINE01_START to match (the
    script refuses to build when the horizon would not fit, rather than
    silently shifting it).

WHAT IS SIMULATED, AND WHAT IS NOT
    Simulated, and labelled so everywhere the repository labels a demo:
        the sonar      samples/synthetic_xtf/SYNTHETIC_mannar_line01.xtf and
                       SYNTHETIC_mannar_line02.xtf (regenerated by this script)
        the detector   a stand-in that reports the file's ground-truth targets
        the changes    T5 moved, T7 removed, T8 new: written into line 02 by
                       tools/make_synthetic_xtf.py --scenario repeat

    Real, and run exactly as they run on a real survey:
        raw XTF ingest, slant-range correction, ping navigation, tiling,
        verification, deduplication, geotagging, dimensions, reports, and every
        GhostTrace stage -- the water-column activity measured on the XTF's own
        water column, habitat from bundled UNEP-WCMC / OSM layers, drift on the
        bundled HYCOM currents, safety, change, priority, alerts and recovery.

WHY A STAND-IN DETECTOR
    DeepEcho's shipped checkpoints were trained on SCTD (aircraft, human, ship)
    and do not have a net class, so they cannot find a ghost net and GhostTrace
    would have nothing to act on. The stand-in exists to show what happens
    AFTER a net is detected. It is replaced by a trained net / pipe / cylinder
    checkpoint, with no other change, by running run_survey.py instead.

    The stand-in reports every man-made truth target at a fixed confidence and
    never the rock cluster, so nothing about the verification filter's rock
    handling can be read from this demo.
"""

from __future__ import annotations

import argparse
import json
import logging
import math
import shutil
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from survey_hazard_map.hazard_geo import enu_delta  # noqa: E402
from survey_hazard_map.hazard_map import build_hazard_map  # noqa: E402
from survey_hazard_map.hazard_mapview import render_map  # noqa: E402
from survey_hazard_map.survey_preparation import prepare_survey  # noqa: E402
from tools.make_synthetic_xtf import make_synthetic_xtf  # noqa: E402

SAMPLES = ROOT / "samples" / "synthetic_xtf"
DEFAULT_ROOT = ROOT / "data" / "surveys"

# Inside the bundled HYCOM window 2026-09-05T00Z .. 2026-09-19T12Z, with room
# for a 240 h horizon after the repeat.
LINE01_START = datetime(2026, 9, 6, 4, 30, tzinfo=timezone.utc)
REPEAT_DELAY = timedelta(days=3)
HORIZON_HOURS = 240.0

SURVEYS = (
    {"dir": "demo-ghosttrace-mannar", "name": "SYNTHETIC_mannar_line01", "scenario": "baseline",
     "start": LINE01_START,
     "title": "SYNTHETIC DEMO — Gulf of Mannar line 01 (GhostTrace)"},
    {"dir": "demo-ghosttrace-mannar-repeat", "name": "SYNTHETIC_mannar_line02", "scenario": "repeat",
     "start": LINE01_START + REPEAT_DELAY,
     "title": "SYNTHETIC DEMO — Gulf of Mannar line 02, repeat survey 3 days later (GhostTrace)"},
)

# The confidence the stand-in reports. Fixed, so the demo is identical each run.
STAND_IN_CONFIDENCE = 0.82

log = logging.getLogger("deepecho.demo")


def truth_pixel(sidecar: dict, lat: float, lon: float) -> tuple[float, float]:
    """A truth position as a continuous strip pixel, via the sidecar's rows.

    The abeam row is the one where the target's along-track offset is least;
    x follows from the across-track offset and the strip's resolution.
    """
    best = None
    for row in sidecar["rows"]:
        if row["lat"] is None or row["heading_deg"] is None:
            continue
        east, north = enu_delta(row["lat"], row["lon"], lat, lon)
        heading = math.radians(row["heading_deg"])
        along = east * math.sin(heading) + north * math.cos(heading)
        across = east * math.cos(heading) - north * math.sin(heading)
        if best is None or abs(along) < abs(best[1]):
            best = (row["row"], along, across)
    row, along, across = best
    return (sidecar["nadir_col"] + across / sidecar["m_per_px_across"],
            row + 0.5 + along / sidecar["m_per_px_along"])


class TruthStandIn:
    """Reports the synthetic file's man-made targets as a detector would."""

    name = "SYNTHETIC ground-truth stand-in (not a model)"
    conf = STAND_IN_CONFIDENCE

    def __init__(self, manifest_rows: list[dict], sidecar: dict, truth: dict) -> None:
        self.rows = {r["tile"]: r for r in manifest_rows}
        across, along = sidecar["m_per_px_across"], sidecar["m_per_px_along"]
        self.boxes = []
        for target in truth["targets"]:
            if not target.get("man_made"):
                continue
            cx, cy = truth_pixel(sidecar, target["latitude"], target["longitude"])
            # A box around the object's footprint, generous on the short axis
            # so a detector-sized box is drawn rather than a sliver.
            half = max(target["length_m"], target["width_m"]) / 2.0
            self.boxes.append((target["class"], cx - half / across - 4, cy - half / along - 4,
                               cx + half / across + 4, cy + half / along + 4))
        self.classes = sorted({b[0] for b in self.boxes})

    def __call__(self, tile_path: Path) -> list[dict]:
        row = self.rows.get(tile_path.name)
        if row is None:
            return []
        tx, ty = int(row["x"]), int(row["y"])
        tw, th = int(row["tile_width"]), int(row["tile_height"])
        found = []
        for cls, x1, y1, x2, y2 in self.boxes:
            cx, cy = (x1 + x2) / 2, (y1 + y2) / 2
            if tx <= cx < tx + tw and ty <= cy < ty + th:
                found.append({"class": cls, "confidence": STAND_IN_CONFIDENCE,
                              "bbox": [max(0.0, x1 - tx), max(0.0, y1 - ty),
                                       min(float(tw), x2 - tx), min(float(th), y2 - ty)],
                              "model": "truth-stand-in"})
        return found


def check_current_window(start: datetime, end: datetime) -> None:
    """Refuse to build when a survey's drift horizon would leave the bundled currents."""
    from ghosttrace.currents import FieldCollection, load_default_field, to_epoch_seconds
    from tools.make_synthetic_xtf import ORIGIN_LAT, ORIGIN_LON

    field = load_default_field()
    if isinstance(field, FieldCollection):
        field = field.field_for(ORIGIN_LAT, ORIGIN_LON)
    if field is None:
        raise SystemExit("no bundled current data covers the demo line; run "
                         "tools/fetch_ghosttrace_data.py --only currents")
    t0, t1 = float(field.times_s[0]), float(field.times_s[-1])
    if not (t0 <= to_epoch_seconds(start) and to_epoch_seconds(end) <= t1):
        first, last = (t.isoformat() for t in field.time_range)
        raise SystemExit(
            f"bundled currents ({first} .. {last}) do not cover {start.isoformat()} .. "
            f"{end.isoformat()}; re-fetch currents (tools/fetch_ghosttrace_data.py --only currents) "
            "or move LINE01_START in this script")


def build_survey(spec: dict, root: Path) -> dict:
    """Generate one synthetic line, process it with the stand-in detector, map it."""
    out = root / spec["dir"]
    export_path = out / "export.json"
    if export_path.is_file():
        existing = json.loads(export_path.read_text(encoding="utf-8"))
        if not existing.get("metadata", {}).get("demo"):
            raise SystemExit(f"{out} holds a real survey export; refusing to overwrite it")
    if out.exists():
        shutil.rmtree(out)

    xtf, truth_path = make_synthetic_xtf(SAMPLES, name=spec["name"], start_time=spec["start"],
                                         scenario=spec["scenario"])
    tiles_dir, _ = prepare_survey([xtf], out)
    manifest = json.loads((out / "manifest.json").read_text(encoding="utf-8"))
    _, sidecar_rel = next(iter(manifest["survey"]["navigation"]["sidecars"].items()))
    sidecar = json.loads((out / sidecar_rel).read_text(encoding="utf-8"))
    truth = json.loads(truth_path.read_text(encoding="utf-8"))

    detector = TruthStandIn(manifest["tiles"], sidecar, truth)
    export = build_hazard_map("truth-stand-in", tiles_dir, out, out / "manifest.json",
                              detector=detector, demo=True, title=spec["title"])
    render_map(export, out, tiles_dir, out / "manifest.json", title=spec["title"])
    return export


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--surveys-root", type=Path, default=DEFAULT_ROOT)
    parser.add_argument("--quiet", action="store_true")
    args = parser.parse_args(argv)
    logging.basicConfig(level=logging.WARNING if args.quiet else logging.INFO,
                        format="%(levelname)-7s %(message)s")

    from ghosttrace.engine import run_ghosttrace

    root = args.surveys_root
    root.mkdir(parents=True, exist_ok=True)
    check_current_window(SURVEYS[0]["start"],
                         SURVEYS[-1]["start"] + timedelta(hours=HORIZON_HOURS + 1))
    # Build both before tracing either, then trace in time order, so the repeat
    # is compared with a line 01 whose ghosttrace.json is already written.
    exports = [build_survey(spec, root) for spec in SURVEYS]
    for spec, export in zip(SURVEYS, exports):
        traced = run_ghosttrace(root / spec["dir"], surveys_root=root, horizon_hours=HORIZON_HOURS)
        summary = traced.get("summary", {})
        cs = traced.get("change_summary", {})
        print(f"\n{spec['title']}\n  detections: {len(export['detections'])}  "
              f"ghosttrace targets: {summary.get('targets')}  urgent: {summary.get('urgent')}  "
              f"actively fishing: {summary.get('actively_fishing')}\n"
              f"  change vs {cs.get('compared_with')}: new {cs.get('new')}, moved {cs.get('moved')}, "
              f"persistent {cs.get('persistent')}, removed {cs.get('removed')}\n"
              f"  written to {root / spec['dir']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
